### ISSUE TITLE
What license is java-diff-utils released under?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mizukyf/java-diff-utils#35]
```
The project says its Apache v2.0
However 
https://code.google.com/p/java-diff-utils/source/browse/branches/1.2/src/difflib
/myers/package.html says its GNU 3.0
Can you confirm which licence takes precedence?

Thanks
```

Original issue reported on code.google.com by `psii...@gmail.com` on 15 Jan 2015 at 5:04

**Comment by mizukyf** [comment]
`myers`パッケージのライセンスに関する矛盾。
コミットの記録を追うと`java-diff-utils`の初期のコミットのなかでASL1.1→GPLへの不可解な変更が行われていた。そもそもこのような変更は不可能と思われるためASL1.1に戻した。
ライセンス情報とパッケージ情報を記載しているファイルのまたフォーマットも変更した。

b1c949b641be7593b22ed0f96eb3bc91b3958ac5
4a23d15adf463af3657a180fd73a54dceed8bc3c
